Talend/connectors-se

lombok.config

This is for jacoco to ignore coverage on generated methods

add lombok.@Generated to method generated by lmobok.

---

localio/src/main/resources/org/talend/components/localio/Messages.properties
pom.xml

Add missing properties that break master build.

fix(properties): Add missing properties.

---

processing-beam/src/main/java/org/talend/components/processing/flatten/FlattenConfiguration.java
processing-beam/src/main/java/org/talend/components/processing/flatten/FlattenDoFn.java
processing-beam/src/main/java/org/talend/components/processing/flatten/FlattenUtils.java
processing-beam/src/main/resources/org/talend/components/processing/flatten/Messages.properties
processing-beam/src/test/java/org/talend/components/processing/flatten/FlattenUtilsTest.java

- Remove technical labels
- Add appropriate doc
- Fix discard trailing strings functionality (iso Studio)

fix(TFD-5339) : fix flatten migration bugs

---

processing-beam/src/main/java/org/talend/components/processing/flatten/Flatten.java
processing-beam/src/main/java/org/talend/components/processing/flatten/FlattenConfiguration.java
processing-beam/src/main/java/org/talend/components/processing/flatten/FlattenDoFn.java
processing-beam/src/main/resources/org/talend/components/processing/flatten/Messages.properties
processing-beam/src/test/java/org/talend/components/processing/flatten/FlattenDoFnTest.java
processing-tck/src/main/java/org/talend/components/processing/normalize/Normalize.java
processing-tck/src/main/java/org/talend/components/processing/normalize/NormalizeConfiguration.java
processing-tck/src/test/java/org/talend/components/processing/normalize/NormalizeTest.java

fix : rename flatten to normalize

---

Jenkinsfile

https://jira.talendforge.org/browse/TCOMP-1236

feat(TCOMP-1236) : Publish only docker.html

---

pom.xml

https://jira.talendforge.org/browse/DEVOPS-5938

DEVOPS-5938 : align distributionManagement repo with connectors-ee ones

---

salesforce/src/main/java/org/talend/components/salesforce/input/AbstractQueryEmitter.java
salesforce/src/main/java/org/talend/components/salesforce/input/ModuleQueryEmitter.java
salesforce/src/main/java/org/talend/components/salesforce/input/SOQLQueryEmitter.java
salesforce/src/main/java/org/talend/components/salesforce/service/BulkQueryService.java
salesforce/src/main/java/org/talend/components/salesforce/service/SalesforceService.java
salesforce/src/test/java/org/talend/components/salesforce/input/SalesforceInputEmitterTest.java

for issue: https://jira.talendforge.org/browse/TDI-41657
can't read null value from primitive type 
use pre-build schema for record.

fix(TDI-41657):[Salesforce:Tacokit] salesforce input can't read null primitive type

---

jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/QueryManager.java

https://jira.talendforge.org/browse/TDI-41695

fix(TDI-41695) : fix type mapping for input

---

jdbc/src/main/java/org/talend/components/jdbc/output/platforms/RedshiftPlatform.java
jdbc/src/main/resources/org/talend/components/jdbc/service/Messages.properties

https://jira.talendforge.org/browse/TDI-41722

fix(TDI-41722): fix redshift table concurent creation issue

---

jdbc/src/main/java/org/talend/components/jdbc/configuration/OutputConfig.java
jdbc/src/main/java/org/talend/components/jdbc/dataset/SqlQueryDataset.java
jdbc/src/main/java/org/talend/components/jdbc/dataset/TableNameDataset.java
jdbc/src/main/java/org/talend/components/jdbc/datastore/JdbcConnection.java
jdbc/src/main/java/org/talend/components/jdbc/service/JdbcService.java
jdbc/src/main/resources/org/talend/components/jdbc/datastore/Messages.properties

https://jira.talendforge.org/browse/TDI-41729

TDI-41729 make jdbc connection timeouts configurable

---

pom.xml

The daikon version is really old, let's upgrade it.

chore(daikon): Upgrade to 0.31.0.

---

jdbc/src/main/java/org/talend/components/jdbc/datastore/JdbcConnection.java

https://jira.talendforge.org/browse/TDI-41729

fix(TDI-41729): add min value for connection timeouts

---

jdbc/src/main/resources/org/talend/components/jdbc/Messages.properties

https://jira.talendforge.org/browse/TDI-41633

TDI-41633 : fix connection and check connection label

---

pom.xml
salesforce/src/main/java/org/talend/components/salesforce/dataset/ModuleDataSet.java
salesforce/src/main/java/org/talend/components/salesforce/input/ModuleQueryEmitter.java
salesforce/src/main/java/org/talend/components/salesforce/service/UiActionService.java
salesforce/src/main/resources/org/talend/components/salesforce/Messages.properties
salesforce/src/main/resources/org/talend/components/salesforce/dataset/Messages.properties
salesforce/src/test/java/org/talend/components/salesforce/SalesforceTestBase.java
salesforce/src/test/java/org/talend/components/salesforce/input/SalesforceInputEmitterTest.java
salesforce/src/test/java/org/talend/components/salesforce/output/SalesforceOutputProcessorTest.java
salesforce/src/test/java/org/talend/components/salesforce/service/UiActionServiceTest.java

For feature: https://jira.talendforge.org/browse/TDI-41712
Improve multiSelect widget for salesforce

feat(TDI-41712):Improve multiSelect widget for salesforce

---

salesforce/src/main/java/org/talend/components/salesforce/configuration/InputConfig.java
salesforce/src/main/java/org/talend/components/salesforce/configuration/InputModuleConfig.java
salesforce/src/main/java/org/talend/components/salesforce/configuration/InputSOQLConfig.java
salesforce/src/main/java/org/talend/components/salesforce/configuration/OutputConfig.java
salesforce/src/main/java/org/talend/components/salesforce/input/AbstractQueryEmitter.java
salesforce/src/main/java/org/talend/components/salesforce/input/ModuleQueryEmitter.java
salesforce/src/main/java/org/talend/components/salesforce/input/SOQLQueryEmitter.java
salesforce/src/main/java/org/talend/components/salesforce/output/SalesforceOutput.java
salesforce/src/main/java/org/talend/components/salesforce/service/SalesforceOutputService.java
salesforce/src/main/resources/org/talend/components/salesforce/configuration/Messages.properties
salesforce/src/main/resources/org/talend/components/salesforce/output/Messages.properties
salesforce/src/test/java/org/talend/components/salesforce/SalesforceTestBase.java
salesforce/src/test/java/org/talend/components/salesforce/input/SalesforceInputEmitterTest.java
salesforce/src/test/java/org/talend/components/salesforce/output/SalesforceOutputProcessorTest.java

For jira: https://jira.talendforge.org/browse/TDI-41727
refactor saelsforce input configuration to solve:
When salesforceinput in pipeline designer, some configuration info shoud not display in INFO tab

fix(TDI-41727):[Salesforce:Tacokit] When salesforce as source in pipeline,some configuration info display in INFO tab

---

salesforce/src/main/resources/org/talend/components/salesforce/Messages.properties

for https://jira.talendforge.org/browse/TDI-41633

fix(TDI-41633):[Tacokit] fix connection type names

---

jdbc/src/main/java/org/talend/components/jdbc/configuration/DistributionStrategy.java
jdbc/src/main/java/org/talend/components/jdbc/configuration/OutputConfig.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/RedshiftPlatform.java
jdbc/src/main/resources/org/talend/components/jdbc/configuration/Messages.properties

https://jira.talendforge.org/browse/TDI-41871

tdi-41871 redshift diststyle

---

jdbc/src/main/java/org/talend/components/jdbc/configuration/OutputConfig.java

https://jira.talendforge.org/browse/TDI-42012

fix(TDI-42012) : fix keys config for update

---

pom.xml

**Debug :**
`java.lang.NoClassDefFoundError: org/apache/beam/sdk/Pipeline$KeysExtractor
at java.lang.Class.getDeclaringClass0(Native Method)
at java.lang.Class.getDeclaringClass(Class.java:1235)
at java.lang.Class.getEnclosingClass(Class.java:1277)
at java.lang.Class.getSimpleBinaryName(Class.java:1443)
at java.lang.Class.getSimpleName(Class.java:1309)
at org.apache.maven.surefire.report.SmartStackTraceParser.toMinimalThrowableMiniMessage(SmartStackTraceParser.java:156)
at org.apache.maven.surefire.report.SmartStackTraceParser.getString(SmartStackTraceParser.java:147)
at org.apache.maven.surefire.report.PojoStackTraceWriter.smartTrimmedStackTrace(PojoStackTraceWriter.java:77)
at org.apache.maven.surefire.booter.ForkingRunListener.encode(ForkingRunListener.java:409)
at …

set test order to alphabetical

---

jdbc/src/main/java/org/talend/components/jdbc/output/platforms/DerbyPlatform.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/MySQLPlatform.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/Platform.java
jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeCopy.java
jdbc/src/main/java/org/talend/components/jdbc/service/JdbcService.java

https://jira.talendforge.org/browse/TDI-42115?filter=-1

fix(TDI-42115) fix jdbc javadoc

---

jdbc/src/main/java/org/talend/components/jdbc/configuration/OutputConfig.java
jdbc/src/main/java/org/talend/components/jdbc/configuration/RedshiftSortStrategy.java
jdbc/src/main/java/org/talend/components/jdbc/output/Output.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/Platform.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/RedshiftPlatform.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/Table.java
jdbc/src/main/resources/org/talend/components/jdbc/configuration/Messages.properties
jdbc/src/test/java/org/talend/components/jdbc/testsuite/OutputTest.java
jdbc/src/test/java/org/talend/components/jdbc/testsuite/PlatformTests.java
jdbc/src/test/java/org/talend/components/jdbc/testsuite/UIActionServiceTest.java

https://jira.talendforge.org/browse/TDI-41903

fix(TDI-41903) : add sort strategy to redshift

---

jdbc/src/main/java/org/talend/components/jdbc/output/Output.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/MySQLPlatform.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/Platform.java
jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeInsert.java

https://jira.talendforge.org/browse/TDI-42227

fix(TDI-42227): better handling of COPY cmd errors

---

azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/output/AzureEventHubsOutput.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/output/AzureEventHubsOutputConfiguration.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/service/Messages.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/service/UiActionService.java
azure-eventhubs/src/main/resources/TALEND-INF/local-configuration.properties
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/Messages.properties
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/output/Messages.properties
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/service/Messages.properties
azure-eventhubs/src/test/java/org/talend/components/azure/eventhubs/output/AzureEventHubsOutputTest.java
azure-eventhubs/src/test/java/org/talend/components/azure/eventhubs/source/AzureEventHubsSourceTest.java

https://jira.talendforge.org/browse/TDI-41797

 feat(TDI-42148): New Azure Event Hub for Streams [ Output ]

---

azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/common/AzureEventHubsConstant.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/dataset/AzureEventHubsDataSet.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/datastore/AzureEventHubsDataStore.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/output/AzureEventHubsOutput.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/output/AzureEventHubsOutputConfiguration.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/service/Messages.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/service/UiActionService.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/source/AzureEventHubsInputConfiguration.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/source/AzureEventHubsInputMapper.java
azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/source/AzureEventHubsSource.java
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/Messages.properties
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/dataset/Messages.properties
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/output/Messages.properties
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/service/Messages.properties
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/source/Messages.properties
azure-eventhubs/src/test/java/org/talend/components/azure/eventhubs/AzureEventHubsTestBase.java
azure-eventhubs/src/test/java/org/talend/components/azure/eventhubs/output/AzureEventHubsOutputTest.java
azure-eventhubs/src/test/java/org/talend/components/azure/eventhubs/service/UiActionServiceTest.java
azure-eventhubs/src/test/java/org/talend/components/azure/eventhubs/source/AzureEventHubsSourceTest.java

for jira: https://jira.talendforge.org/browse/TDI-42330
* move partitionId from dataset to input config
* add checkbox to control read from one partition or all partitions
* improve manually unit tests
* improve i18n

 fix(TDI-42330):improve config of eventhub input/output

---

azure-eventhubs/src/main/java/org/talend/components/azure/eventhubs/source/AzureEventHubsInputConfiguration.java
azure-eventhubs/src/main/resources/org/talend/components/azure/eventhubs/output/Messages.properties

* also hide 'inclusive Flag' for ready by offset which is not be used.

fix(TDI-42330):change default value of 'inclusive Flag' and empty useless hint

---

pom.xml

https://jira.talendforge.org/browse/TDI-42341

feat(TDI-42341) : scan-descriptor

---

azure/azureblob/src/main/java/org/talend/components/azure/runtime/converters/AvroConverter.java
azure/azurecommon/src/main/java/org/talend/components/adlsgen2/common/connection/AdlsGen2Connection.java
jdbc/src/main/java/org/talend/components/jdbc/configuration/OutputConfig.java

https://jira.talendforge.org/browse/TDI-42405

fix(TDI-42405):workaround for blank page issue

---

salesforce/pom.xml
salesforce/src/main/java/org/talend/components/salesforce/service/SalesforceService.java
salesforce/src/main/resources/TALEND-INF/local-configuration.properties
salesforce/src/test/java/org/talend/components/salesforce/service/SalesforceServiceTest.java

for jira: https://jira.talendforge.org/browse/TDI-42467

feat(TDI-42467):Update SalesForce API for Tacokit/TPD(45.0)

---

salesforce/src/main/resources/org/talend/components/salesforce/configuration/Messages.properties
salesforce/src/main/resources/org/talend/components/salesforce/dataset/Messages.properties
salesforce/src/main/resources/org/talend/components/salesforce/datastore/Messages.properties
salesforce/src/main/resources/org/talend/components/salesforce/input/Messages.properties

for jira: https://jira.talendforge.org/browse/TDI-42488

fix(TDI-42488):salesforce i18n issue

---

marketo/src/main/java/org/talend/components/marketo/output/LeadStrategy.java
marketo/src/test/java/org/talend/components/marketo/MarketoBaseTest.java
marketo/src/test/java/org/talend/components/marketo/PeopleTestIT.java

https://jira.talendforge.org/browse/TDI-42514

fix(TDI-42514): fix null ListId

---

jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/QueryManagerImpl.java

https://jira.talendforge.org/browse/TDI-42394

fix(TDI-42394):Cnnot rollback SQLDWH

---

azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/common/format/csv/CsvConverter.java

https://jira.talendforge.org/browse/TDI-42518

fix(TDI-42518): add withNullable to schema infered by CsvConfiguration

---

couchbase/src/main/java/org/talend/components/couchbase/package-info.java

https://jira.talendforge.org/browse/TDI-42529
On Studio's palette Couchbase was in wrong folder.

fix(TDI-42529): move Couchbase from Databases to Databases NoSQL

---

Jenkinsfile
pom.xml

[TDI-42571](https://jira.talendforge.org/browse/TDI-42571) : [Spotbugs](https://spotbugs.github.io/) static analyser add in pom.xml of the connector-se project.
Results are available in [jenkins report](https://jenkins-common.datapwn.com/job/connectors-se/job/TDI-42571_StaticCodeAnalyser/7/Maven_20Site/) , go to any module (Components :: Salesforce for example), then "Project Reports" -> SpotBugs.

Tdi 42571 static code analyser

---

jdbc/src/main/resources/TALEND-INF/local-configuration.properties

https://jira.talendforge.org/browse/TDI-42646

fix(TDI-42646):Rename SQLDWH to Azure SQL Data Warehouse

---

jdbc/src/main/resources/org/talend/components/jdbc/datastore/Messages.properties

refer to https://jira.talendforge.org/browse/TFD-8167

chore(TFD-8167): give blank for placeholder of username/password/handler on JDBC

---

azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/AvroBlobFileReader.java
azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/BlobFileReader.java
azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/CSVBlobFileReader.java
azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/ExcelBlobFileReader.java
azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/ExcelHTMLBlobFileReader.java
azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/ParquetBlobFileReader.java
azure/azureblob/src/main/java/org/talend/components/azure/service/MessageService.java
azure/azureblob/src/main/java/org/talend/components/azure/source/BlobSource.java
azure/azureblob/src/main/resources/org/talend/components/azure/service/Messages.properties
azure/azureblob/src/test/java/org/talend/components/azure/source/CSVInputIT.java

* Fix error message when container doesn't exist

fix(TDI-42618): Fix error message when container name invalid

---

marketo/src/main/java/org/talend/components/marketo/dataset/MarketoDataSet.java
marketo/src/main/java/org/talend/components/marketo/input/LeadSource.java
marketo/src/main/java/org/talend/components/marketo/input/MarketoSource.java
marketo/src/main/java/org/talend/components/marketo/service/MarketoService.java

https://jira.talendforge.org/browse/TDI-42595

chore(TDI-42595): Marketo dynamic schema

---

jdbc/src/main/java/org/talend/components/jdbc/service/I18nMessage.java
jdbc/src/main/resources/org/talend/components/jdbc/service/Messages.properties

https://jira.talendforge.org/browse/TDI-42455

fix(TDI-42455):clear error message for SQLDWH

---

azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/datastore/SharedKeyUtils.java
azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/datastore/SharedKeyCredentialsUtilsTest.java

https://jira.talendforge.org/browse/TDI-42803

fix(TDI-42795): handle blobName with space(s)

---

azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/I18n.java
azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/UIActionService.java
azure-dls-gen2/src/main/resources/org/talend/components/adlsgen2/service/Messages.properties

https://jira.talendforge.org/browse/TDI-42617

fix(TDI-42617): add more explicit message when healthcheck fails

---

jdbc/src/main/java/org/talend/components/jdbc/configuration/OutputConfig.java
jdbc/src/test/java/org/talend/components/jdbc/testsuite/ConfigurationTest.java
pom.xml

https://jira.talendforge.org/browse/TDI-42904

fix(TDI-42904): fix table creation triggering

---

jdbc/src/main/resources/org/talend/components/jdbc/service/Messages.properties
jdbc/src/test/java/org/talend/components/jdbc/testsuite/OutputTest.java

adding a unit test only : https://jira.talendforge.org/browse/TDI-42788

TDI-42788: add unit test for wissing key on delete action usecase

---

azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/datastore/SharedKeyUtils.java
azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/datastore/SharedKeyCredentialsUtilsTest.java

backport of https://jira.talendforge.org/browse/TDI-42803

fix(TDI-42803): handle blobName with space(s) - backport

---

jdbc/src/main/java/org/talend/components/jdbc/service/I18nMessage.java
jdbc/src/main/resources/org/talend/components/jdbc/service/Messages.properties
pom.xml

https://jira.talendforge.org/browse/TDI-42645

fix(TDI-42645): Show clean error message for SQLDWH

---

jdbc/src/main/java/org/talend/components/jdbc/configuration/OutputConfig.java
jdbc/src/main/java/org/talend/components/jdbc/configuration/RedshiftSortStrategy.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/RedshiftPlatform.java
jdbc/src/main/java/org/talend/components/jdbc/service/I18nMessage.java
jdbc/src/main/java/org/talend/components/jdbc/service/UIActionService.java
jdbc/src/main/resources/org/talend/components/jdbc/Messages.properties
jdbc/src/main/resources/org/talend/components/jdbc/configuration/Messages.properties
jdbc/src/main/resources/org/talend/components/jdbc/service/Messages.properties

https://jira.talendforge.org/browse/TDI-41903

redshift support single sort key

---

jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeCopy.java
jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeInsert.java

https://jira.talendforge.org/browse/TDI-42349
Improve Insert operation, by preventing temporary table usage.

feat(TDI-42349): prevent insert operation use temp table

---

Jenkinsfile

update JenkinsFile for release process on maintenance/1.2

chore(TPS-3537): update JenkinsFile for release process on maintenance

---

Jenkinsfile
azure-dls-gen2/pom.xml

set commons-csv from snapshot to release for release process

chore(TPS-3537): remove snapshot deps

---

jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeCopy.java

https://jira.talendforge.org/browse/TDI-43097

fix(TDI-43097):remove shutdown hook for snowflake

---

pom.xml

follow studio component-server version.

chore(tck): bump component-runtime to 1.1.14

---

azure-dls-gen2/pom.xml
azure/azureblob/pom.xml
azure/azurecommon/pom.xml
azure/pom.xml
couchbase/pom.xml
jdbc/pom.xml
marketo/pom.xml
pom.xml
salesforce/pom.xml

due to 
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
```

bump current snapshot

---

jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeInsert.java

https://jira.talendforge.org/browse/TDI-42349
We should not commit records if any rejects. (previous logic).
Added rollback operation for such cases.

feat(TDI-42349): fix rejects flow

---

jdbc/src/main/resources/TALEND-INF/local-configuration.properties

https://jira.talendforge.org/browse/TDI-43098

feat(TDI-43098):add oracle driver to JDBC

---

pom.xml

Generate dita files for doc team
https://jira.talendforge.org/browse/TDI-42717

feat(TDI-42717) : gen dita files

---

package.json

https://jira.talendforge.org/browse/TDI-43171
Upgrade i18n-scripts version

feat(TDI-43171) : bump i18n-scripts version

---

.jenkins/release.sh
Jenkinsfile

https://jira.talendforge.org/browse/TDI-43214
Related `connectors-ee` PRs:
https://github.com/Talend/connectors-ee/pull/206

fix(TDI-43214): improve Jenkins Release stage

---

Jenkinsfile
rest/pom.xml
rest/src/main/java/org/talend/components/rest/configuration/RequestBody.java
rest/src/main/java/org/talend/components/rest/configuration/RequestConfig.java
rest/src/main/java/org/talend/components/rest/service/Body.java
rest/src/main/java/org/talend/components/rest/service/RestService.java
rest/src/test/java/org/talend/components/rest/service/ClientTestWithEmbededServerTest.java
rest/src/test/java/org/talend/components/rest/service/ClientTestWithHttpbinTest.java
rest/src/test/java/org/talend/components/rest/service/ClientTestWithMockProxy.java
rest/src/test/java/org/talend/components/rest/service/RestServiceTest.java

The talend httpbin vm is not accessible from the CI. So no testcontainer is use to get the httpbin container at unit test runtime. But not running within our CI. SO exclude httpbin test by default.

feat(TDI-42996) : httpbin container + exclude ITs

---

Jenkinsfile

Add secret to pull image from registry.

feat(TDI-43214) : add secret

---

Jenkinsfile

fix : fix i18n deploy with distributionManagement

---

.jenkins/release.sh
Jenkinsfile

fix(TDI-43214): chore connectors-ee release script

---

.jenkins/release.sh
Jenkinsfile
package.json

https://jira.talendforge.org/browse/TDI-43307

fix(TDI-43307): update i18n-scripts

---

salesforce/src/main/java/org/talend/components/salesforce/input/ModuleQueryEmitter.java
salesforce/src/test/java/org/talend/components/salesforce/input/SalesforceInputEmitterTest.java

for https://jira.talendforge.org/browse/TDI-42640
When use salesforce module dataset, and selected fields is empty, this would query all avalilable feilds in input

fix(TDI-42640):[salesforce tacokit] dataset dynamic schema retrieved null

---

Jenkinsfile

https://jira.talendforge.org/browse/TDI-43345

feat(TDI-43345): schedule push to xtm on master

---

jdbc/src/main/resources/org/talend/components/jdbc/configuration/Messages.properties

https://jira.talendforge.org/browse/TDI-43397

fix(TDI-43397):fill the placeholder for JDBC components

---

salesforce/src/main/java/org/talend/components/salesforce/input/AbstractQueryEmitter.java
salesforce/src/main/java/org/talend/components/salesforce/service/Messages.java
salesforce/src/main/java/org/talend/components/salesforce/service/SalesforceService.java
salesforce/src/main/resources/org/talend/components/salesforce/service/Messages.properties
salesforce/src/test/java/org/talend/components/salesforce/SalesforceTestBase.java
salesforce/src/test/java/org/talend/components/salesforce/service/UiActionServiceTest.java

for jira: https://jira.talendforge.org/browse/TDI-43375

fix(TDI-43375):check salesforce connection successfully when we use an expired password

---

.jenkins/release.sh

https://jira.talendforge.org/browse/TDI-43420

fix(TDI-43420): jenkins - tweak release build

---

marketo/src/main/resources/org/talend/components/marketo/dataset/Messages.properties

https://jira.talendforge.org/browse/TDI-43402

fix(TDI-43402): add workaround for missing placeholders for Marketo

---

salesforce/src/main/resources/org/talend/components/salesforce/configuration/Messages.properties
salesforce/src/main/resources/org/talend/components/salesforce/dataset/Messages.properties

for jira: https://jira.talendforge.org/browse/TDI-43404

fix(TDI-43404):missing placeholders which would break build in salesforce

---

jdbc/src/main/java/org/talend/components/jdbc/service/JdbcService.java

https://jira.talendforge.org/browse/TDI-42001
Confirmed the fix work on TPD

fix(TDI-42001) : add allow local file parameter to false

---

azure-dls-gen2/src/main/resources/org/talend/components/adlsgen2/output/Messages.properties

https://jira.talendforge.org/browse/TDI-43403

fix(TDI-43403): workaround for missing placeholders for azure-dls-gen2

---

couchbase/src/main/resources/org/talend/components/couchbase/dataset/Messages.properties
couchbase/src/main/resources/org/talend/components/couchbase/datastore/Messages.properties
couchbase/src/main/resources/org/talend/components/couchbase/output/Messages.properties
couchbase/src/main/resources/org/talend/components/couchbase/source/Messages.properties

https://jira.talendforge.org/browse/TDI-43398

fix(TDI-43398): add placeholders

---

connectors-test-bom/pom.xml

https://jira.talendforge.org/browse/TDI-43392
Upgrading the last entrance of hadoop libraries.

fix(TDI-43392): upgrade test bom

---

workday/src/main/resources/org/talend/components/workday/Messages.properties

renaming as describe in https://jira.talendforge.org/browse/TDI-43498

TDI-43498 : Workday connection to Workday

---

Jenkinsfile

chore(TDI-43439): add source clear scan

---

jdbc/src/main/java/org/talend/components/jdbc/input/AbstractInputEmitter.java

https://jira.talendforge.org/browse/TDI-43525

fix(TDI-43525): ClassCastException on short type JDBC

---

rest/src/main/java/org/talend/components/rest/configuration/RequestConfig.java

https://jira.talendforge.org/browse/TDI-43401

fix(TDI-43401) : Add REST advanced settings

---

salesforce/pom.xml
salesforce/src/main/java/org/talend/components/salesforce/service/SalesforceService.java
salesforce/src/main/resources/TALEND-INF/local-configuration.properties
salesforce/src/test/java/org/talend/components/salesforce/service/SalesforceServiceTest.java

for jira https://jira.talendforge.org/browse/TDI-43516
update salesforce api to 47.0

feat(TDI-43516):Upgrade salesforce to latest endpoint

---

common-stream-io/common-io/src/main/java/org/talend/components/common/stream/format/OptionalLine.java

Error in name.
(Should envisage kind of unit tests for that)

Optional line correction

---

pom.xml
workday/pom.xml

Fix locales versions - [TDI-43698](https://jira.talendforge.org/browse/TDI-43698)

fix(TDI43698) - locales version ranges

---

couchbase/src/main/java/org/talend/components/couchbase/source/CouchbaseInputConfiguration.java
couchbase/src/main/resources/org/talend/components/couchbase/processor/Messages.properties

https://jira.talendforge.org/browse/TDI-43743

fix(TDI-43743): remove empty file | remove TextArea annotation

---

netsuite/pom.xml
netsuite/src/test/java/org/talend/components/netsuite/processor/NetSuiteOutputProcessorTest.java
netsuite/src/test/java/org/talend/components/netsuite/service/NetSuiteClientConnectionServiceTest.java
netsuite/src/test/java/org/talend/components/netsuite/service/UIActionServiceTest.java
netsuite/src/test/java/org/talend/components/netsuite/source/NetSuiteSourceTest.java

It disables all Netsuite tests. It is needed to fix problems with tests in the Jenkins build

feat(TDI-40709): Netsuite. disable test temporarily

---

.jenkins/xtm-deploy.sh
Jenkinsfile
pom.xml

fix locales deployment repository

Prepare release 1.7.0

---

netsuite/src/test/java/org/talend/components/netsuite/processor/NetSuiteOutputProcessorTest.java
netsuite/src/test/java/org/talend/components/netsuite/service/NetSuiteClientConnectionServiceTest.java
netsuite/src/test/java/org/talend/components/netsuite/service/UIActionServiceTest.java
netsuite/src/test/java/org/talend/components/netsuite/source/NetSuiteSourceTest.java

Reverts Talend/connectors-se#349
Making release build failing.

Revert "feat(TDI-40709): Netsuite. enable tests"

---

azure-dls-gen2/pom.xml
azure/azureblob/pom.xml
common-stream-io/stream-avro/pom.xml
connectors-test-bom/pom.xml
pom.xml
pubsub/pom.xml
salesforce/pom.xml

https://jira.talendforge.org/browse/TDI-43762

fix(TDI-43762): update codehaus jackson

---

bigquery/src/main/java/org/talend/components/bigquery/avro/AvroConverter.java
bigquery/src/main/java/org/talend/components/bigquery/avro/RecordConverter.java
bigquery/src/main/java/org/talend/components/bigquery/dataset/QueryDataSet.java
bigquery/src/main/java/org/talend/components/bigquery/dataset/TableDataSet.java
bigquery/src/main/java/org/talend/components/bigquery/datastore/BigQueryConnection.java
bigquery/src/main/java/org/talend/components/bigquery/input/BigQueryQueryInput.java
bigquery/src/main/java/org/talend/components/bigquery/input/BigQueryQueryInputConfig.java
bigquery/src/main/java/org/talend/components/bigquery/input/BigQueryTableExtractInput.java
bigquery/src/main/java/org/talend/components/bigquery/input/BigQueryTableExtractInputConfig.java
bigquery/src/main/java/org/talend/components/bigquery/input/BigQueryTableExtractMapper.java
bigquery/src/main/java/org/talend/components/bigquery/input/BigQueryTableInput.java
bigquery/src/main/java/org/talend/components/bigquery/input/BigQueryTableInputConfig.java
bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutputConfig.java
bigquery/src/main/java/org/talend/components/bigquery/output/TacoKitRecordToTableRowConverter.java
bigquery/src/main/java/org/talend/components/bigquery/service/BigQueryConnectorException.java
bigquery/src/main/java/org/talend/components/bigquery/service/BigQueryService.java
bigquery/src/main/java/org/talend/components/bigquery/service/GoogleStorageService.java
bigquery/src/main/java/org/talend/components/bigquery/service/I18nMessage.java
bigquery/src/main/resources/org/talend/components/bigquery/Messages.properties
bigquery/src/main/resources/org/talend/components/bigquery/datastore/Messages.properties
bigquery/src/test/java/org/talend/components/bigquery/input/BigQueryQueryInputTest.java
bigquery/src/test/java/org/talend/components/bigquery/input/BigQueryTableExtractInputTest.java
bigquery/src/test/java/org/talend/components/bigquery/input/BigQueryTableExtractMapperTest.java
bigquery/src/test/java/org/talend/components/bigquery/output/BigQueryOutputTest.java
bigquery/src/test/java/org/talend/components/bigquery/output/TacoKitRecordToTableRowConverterTest.java

Changed to Google Big Query
Changed all headers for copyright + automatic formatting

TDI-43836 : change Big Query connection name

---

pubsub/src/main/java/org/talend/components/pubsub/datastore/PubSubDataStore.java

White spaces forbidden in project name

TDI-43660 : pubsub connection - pattern for project name

---

pom.xml

https://jira.talendforge.org/browse/TDI-43921

fix(TDI-43921): update jetty version

---

jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeUpdate.java
jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeUpsert.java

https://jira.talendforge.org/browse/TDI-44005
In the query generation part there was placed wrong collector of joining operation keys. It is updated to correct one.

fix(TDI-44005): add spaces before and after AND

---

jdbc/src/main/resources/TALEND-INF/local-configuration.properties

for https://jira.talendforge.org/browse/TDI-43776
- **rename cloud connector from  Azure SQL DWH to Azure Synapse**

feat(TDI-43776):rename cloud connector from  Azure SQL DWH to Azure Synapse

---

common-stream-io/stream-json/src/main/java/org/talend/components/common/stream/input/json/JsonRecordReader.java
common-stream-io/stream-json/src/main/java/org/talend/components/common/stream/input/json/JsonToRecord.java
common-stream-io/stream-json/src/test/java/org/talend/components/common/stream/input/json/JsonToRecordTest.java

CosmoDB & GoogleStorage uses classes JsonToRecord.

Move back JsonToRecord to initial package

---

netsuite/src/test/java/org/talend/components/netsuite/processor/NetSuiteOutputProcessorTest.java
netsuite/src/test/java/org/talend/components/netsuite/service/NetSuiteClientConnectionServiceTest.java
netsuite/src/test/java/org/talend/components/netsuite/service/UIActionServiceTest.java
netsuite/src/test/java/org/talend/components/netsuite/source/NetSuiteSourceTest.java

Disable netsuite uit test for release 1.8.0

Disable netsuite UT for release

---

pom.xml

- we lower locales.version to previous branch for allowing master build

build(master): temporary fix for XTM locales failing generation

---

pubsub/src/main/java/org/talend/components/pubsub/input/PubSubInput.java
pubsub/src/main/java/org/talend/components/pubsub/input/PubSubPartitionMapper.java

- Generate subscription ID in input component if needed
- Modified generated subscription ID to conform to Google naming rules

TDI-43661 : pubsub dataset : error on sampling if no subscription id

---

netsuite/src/test/java/org/talend/components/netsuite/processor/NetSuiteOutputProcessorTest.java
netsuite/src/test/java/org/talend/components/netsuite/service/NetSuiteClientConnectionServiceTest.java
netsuite/src/test/java/org/talend/components/netsuite/service/UIActionServiceTest.java
netsuite/src/test/java/org/talend/components/netsuite/source/NetSuiteSourceTest.java

This reverts commit 5c906d99
This enables Netsuite tests

Revert "Disable netsuite UT for release (#393)"

---

cosmosDB/pom.xml
cosmosDB/src/main/java/org/talend/components/cosmosDB/service/CosmosDBService.java
cosmosDB/src/main/java/org/talend/components/cosmosDB/service/I18nMessage.java
cosmosDB/src/main/resources/org/talend/components/cosmosDB/service/Messages.properties
cosmosDB/src/test/java/org/talend/components/cosmosDB/CosmosDBServiceTestIT.java

https://jira.talendforge.org/browse/TDI-44110

fix(TDI-44110):Correct dependence and errror message.

---

pubsub/src/main/java/org/talend/components/pubsub/output/message/CSVMessageGenerator.java
pubsub/src/test/java/org/talend/components/pubsub/output/message/CSVMessageGeneratorTest.java

During generation of a CSV message, all arrays and inner records are now omitted.

TDI-43732 : flatten CSV

---

pom.xml

https://jira.talendforge.org/browse/TDI-44184

feat(TDI-44184): Improve code quality

---

common-stream-io/common-io/src/main/resources/org/talend/components/common/stream/format/Messages.properties

translation from https://jira.talendforge.org/browse/TDI-44175

fix(TDI-44175) : english correction.

---

cosmosDB/pom.xml
pom.xml

https://jira.talendforge.org/browse/TDI-44233

fix(TDI-44233): add dependence of httpclient

---

netsuite/src/main/resources/org/talend/components/netsuite/processor/Messages.properties
netsuite/src/main/resources/org/talend/components/netsuite/source/Messages.properties

https://jira.talendforge.org/browse/TDI-44228

fix(TDI-44228):rename netsuite dataset in pipeline

---

pom.xml

Bump locales version to 1.10.2

release/1.10.0, bump to locales 1.10.2

---

Jenkinsfile

REmove target files before push2Xtml

Fix push to xtm

---

jdbc/src/main/java/org/talend/components/jdbc/service/UIActionService.java

https://jira.talendforge.org/browse/TDI-44299

fix(TDI-44299): connection pool is not correctly closed

---

azure-dls-gen2/pom.xml
azure/azureblob/pom.xml
pom.xml

for https://jira.talendforge.org/browse/TDI-44140
update compress jar to 1.19

fix(TDI-44140):update dependency commons-compress to 1.19

---

google-storage/src/main/resources/org/talend/components/google/storage/input/Messages.properties
google-storage/src/main/resources/org/talend/components/google/storage/output/Messages.properties

https://jira.talendforge.org/browse/TDI-44379
Fixed in connectors repository but must be fixed in XTM : https://jira.talendforge.org/browse/I18N-201

fix(TDI-44379) : GCS fix labels

---

jdbc/src/main/java/org/talend/components/jdbc/output/platforms/Platform.java
jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/QueryManagerImpl.java
jdbc/src/main/java/org/talend/components/jdbc/service/JdbcService.java
jdbc/src/main/java/org/talend/components/jdbc/service/UIActionService.java
jdbc/src/main/resources/TALEND-INF/local-configuration.properties

https://jira.talendforge.org/browse/TDI-44431

fix(TDI-44431):Add JTDS driver to connector

---

pom.xml

https://jira.talendforge.org/browse/TDI-43142

fix(TDI-43142):fix jacoco report

---

azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/AdlsGen2Service.java
azure/azureblob/src/test/java/org/talend/components/azure/source/CSVInputIT.java
dynamics-crm/src/test/java/org/talend/components/dynamicscrm/output/DynamicsCrmOutputTestIT.java
ftp/src/test/java/org/talend/components/ftp/output/FTPOutputTest.java
pom.xml

bump : 
- component-runtime to 1.1.23 
- beam to 2.22.0 
- locales version to 1.11.1
fix breaking change from component-runtime 1.1.22

prepare(release 1.11.0): step1

---

jdbc/src/main/java/org/talend/components/jdbc/output/platforms/MSSQLPlatform.java
jdbc/src/main/java/org/talend/components/jdbc/output/platforms/PlatformFactory.java

https://jira.talendforge.org/browse/TDI-44543

fix(TDI-44543):change JTDS to MSSQL platform

---

package.json

* update version for i18n-scripts from 0.7.0 -> 2.0.3

chore(TDI-44565): update i18n-scripts

---

bigquery/pom.xml
jdbc/pom.xml
netsuite/pom.xml
pom.xml
salesforce/pom.xml

* use version [3.9] of commons-lang3 that support Java 11

fix(TDI-44671): update commons-lang3

---

dynamics-crm/pom.xml
jdbc/pom.xml
pom.xml

* update commons-codec to 1.14 version
https://jira.talendforge.org/browse/TDI-44145

chore(TDI-44145): update commons-codec:1.14

---

common-stream-io/stream-line/src/main/java/org/talend/components/common/stream/output/line/RecordSerializerLineHelper.java
common-stream-io/stream-line/src/test/java/org/talend/components/common/stream/output/line/RecordSerializerLineHelperTest.java

https://jira.talendforge.org/browse/TDI-44667

fix(TDI-44667) : fix npe with null value when generate csv

---

jdbc/pom.xml
jdbc/src/main/resources/TALEND-INF/local-configuration.properties

https://jira.talendforge.org/browse/TDI-44731

feat(TDI-44731): upgrade snowflake driver

---

pom.xml

chore(repository): bump component-runtime to 1.1.24

---

jdbc/src/main/java/org/talend/components/jdbc/input/ChangeDataCaptureInputEmitter.java
pom.xml

- also correct bad formatting in jdbc

prepare(release/1.13.0): set locales to 1.13.1 for deterministic release

---

package.json

* bump i18n-scripts from [0.7.0] to [2.0.6]

chore(TDI-44565): bump i18n-scripts

---

jdbc/pom.xml
jdbc/src/main/resources/TALEND-INF/local-configuration.properties

https://jira.talendforge.org/browse/TDI-44839
Update POSTGRESQL driver to version 42.2.14

fix(TDI-44839): update POSTGRESQL driver

---

pom.xml

Release 1.14.0

---

jdbc/src/main/java/org/talend/components/jdbc/datastore/JdbcConnection.java
jdbc/src/main/resources/TALEND-INF/local-configuration.properties

Support of memsql in tck/jdbc : https://jira.talendforge.org/browse/TDI-44842

feat(TDI-44909) : Add memsql support in tck/jdbc

---

pom.xml

release 1.15.0

---

common-stream-io/common-io/src/main/java/org/talend/components/common/stream/format/excel/ExcelConfiguration.java

https://jira.talendforge.org/browse/TDI-45000
Added a default value for excel sheet.

TDI-45000 : default name for excel sheet

---

dynamics-crm/pom.xml

https://jira.talendforge.org/browse/TDI-44873

feat(TDI-44873) : bump talend-mscrm to bump oliingo/odata version

---

Jenkinsfile

https://jira.talendforge.org/browse/TDI-45244

TDI-45244 : change "push XTM" day to monday

---

rest/src/main/java/org/talend/components/rest/service/RestService.java

https://jira.talendforge.org/browse/TDI-45226

feat(TDI-45226) : Clean REST check connection method

---

bigquery/src/test/resources/META-INF/services/org.talend.sdk.component.runtime.serialization.ContainerFinder
common-stream-io/stream-json/src/test/resources/META-INF/services/org.talend.sdk.component.runtime.serialization.ContainerFinder
extensions/polling/src/test/resources/META-INF/services/org.talend.sdk.component.runtime.serialization.ContainerFinder
migration-tester/src/test/resources/META-INF/services/org.talend.sdk.component.runtime.serialization.ContainerFinder
pom.xml
rest/src/test/resources/META-INF/services/org.talend.sdk.component.runtime.serialization.ContainerFinder

Bump to tck 1.1.27 / BEam 2.25.0
https://jira.talendforge.org/browse/TDI-45314

feat(TDI-45314) : bump tck to 1.1.27

---

.jenkins/release.sh

release must skip tests due to dockerhub new policy.

chore(release) : skipTest on release due to new dockerhub policy.

---

pom.xml

chore(release) : bump locales to 1.16.1

---

common-stream-io/stream-json/src/main/java/org/talend/components/common/stream/output/json/RecordToJson.java
common-stream-io/stream-json/src/test/java/org/talend/components/common/stream/output/json/RecordToJsonTest.java

https://jira.talendforge.org/browse/TDI-45221

TDI-45221 : Record to json on date time

---

pom.xml

https://jira.talendforge.org/browse/TDI-45223

fix(TDI-45223):upgrade zookeeper version.

---

bigquery/pom.xml
bigquery/src/bench/java/org.talend.components.bigquery/output/BigQueryOutputITCase.java
bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutputConfig.java
bigquery/src/main/java/org/talend/components/bigquery/service/I18nMessage.java
bigquery/src/main/resources/TALEND-INF/components/format.json
bigquery/src/main/resources/org/talend/components/bigquery/output/Messages.properties
bigquery/src/main/resources/org/talend/components/bigquery/service/Messages.properties
bigquery/src/test/java/org/talend/components/bigquery/output/BigQueryOutputTest.java

https://jira.talendforge.org/browse/TDI-44723
Add truncate option to the bigquery connector

feat(TDI-44723): add truncate option

---

dynamics-crm/pom.xml

depends on commit https://github.com/Talend/tdi-studio-se/pull/5629

chore(TDI-45326): update talend mscrm lib

---

Jenkinsfile

https://jira.talendforge.org/browse/TDI-45403
Make sonar distinguish branches on project
Result here for this test branch 
https://sonar-eks.datapwn.com/dashboard?branch=clesaec%2FTDI-45403_SonarBranch&id=org.talend.components%3Aconnectors-se

TDI-45403 : sonar branch

---

bigquery/src/main/java/org/talend/components/bigquery/avro/AvroConverter.java
bigquery/src/test/java/org/talend/components/bigquery/input/BigQueryTableExtractInputTest.java

Re-creating https://github.com/Talend/connectors-se/pull/491.

fix(TDI-45139): clean pr commits

---

common-stream-io/stream-json/src/main/java/org/talend/components/common/stream/input/json/JsonToRecord.java
common-stream-io/stream-json/src/test/java/org/talend/components/common/stream/input/json/JsonToRecordTest.java

https://jira.talendforge.org/browse/TDI-45199

feat(TDI-45199) : jsonToRecord shoud generate nullable fields

---

pom.xml

chore : bump locales to 1.16.4

---

pom.xml

Reverts Talend/connectors-se#529

Revert "fix(TDI-45418):Upgrade Jackson libraries"

---

common-test/README.md

https://jira.talendforge.org/browse/TDI-45538
Just a basic simple help on usage of common-test module

TDI-45538 : read me on common test module

---

jdbc/src/main/java/org/talend/components/jdbc/input/AbstractInputEmitter.java
jdbc/src/main/java/org/talend/components/jdbc/input/ChangeDataCaptureInputEmitter.java
jdbc/src/main/java/org/talend/components/jdbc/service/JdbcService.java
jdbc/src/main/java/org/talend/components/jdbc/service/UIActionService.java
jdbc/src/main/resources/org/talend/components/jdbc/Messages.properties
jdbc/src/test/java/org/talend/components/jdbc/suite/JDBCBaseContainerTest.java

https://jira.talendforge.org/browse/TDI-45206

feat(TDI-45206): implement guess schema action

---

migration-tester/src/test/java/org/talend/components/migration/source/DummySourceTest.java
pom.xml

Bump repository to component-runtime 1.30.0 w/ related deps.

chore(master): bump component-runtime to 1.30.0

---

pom.xml

https://jira.talendforge.org/browse/TDI-45418

fix(TDI-45418):Upgrade Jackson libraries

---

bigquery/src/main/resources/org/talend/components/bigquery/output/Messages.properties

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-45686
**What is the new behavior?**
Bigquery rename truncate to overwrite
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:

fix(TDI-45686): bigquery rename truncate to overwrite

---

jdbc/src/main/java/org/talend/components/jdbc/dataset/TableNameDataset.java
jdbc/src/main/java/org/talend/components/jdbc/input/AbstractInputEmitter.java
jdbc/src/main/java/org/talend/components/jdbc/service/UIActionService.java
jdbc/src/main/resources/org/talend/components/jdbc/Messages.properties
jdbc/src/main/resources/org/talend/components/jdbc/dataset/Messages.properties

https://jira.talendforge.org/browse/TDI-45586
Make columns property. Select needed columns and use them.

feat(TDI-45586): add support for column selection

---

jdbc/src/main/java/org/talend/components/jdbc/dataset/TableNameDataset.java
jdbc/src/main/java/org/talend/components/jdbc/input/AbstractInputEmitter.java
jdbc/src/main/java/org/talend/components/jdbc/service/UIActionService.java
jdbc/src/main/resources/org/talend/components/jdbc/Messages.properties
jdbc/src/main/resources/org/talend/components/jdbc/dataset/Messages.properties

https://jira.talendforge.org/browse/TDI-45751

chore(TDI-45751): backport to 1.16

---

bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
bigquery/src/main/java/org/talend/components/bigquery/service/I18nMessage.java
bigquery/src/main/resources/org/talend/components/bigquery/service/Messages.properties

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-45658
**What is the new behavior?**
More clear error message whe sorage bucket is empty
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:

fix(TDI-45686): bigquery improve error message when npe

---

extensions/polling/src/main/java/org/talend/components/extension/polling/internal/PollingComponentExtension.java
extensions/polling/src/main/java/org/talend/components/extension/polling/internal/impl/PollingConfiguration.java
extensions/polling/src/main/java/org/talend/components/extension/polling/internal/impl/PollingInput.java
extensions/polling/src/main/resources/org/talend/components/extension/polling/internal/impl/Messages.properties

https://jira.talendforge.org/browse/TDI-45685

feat(TDI-45685) : Row Generator

---

pom.xml

https://jira.talendforge.org/browse/TDI-45655

fix(TDI-45727):CVE jackson-mapper-asl

---

jdbc/pom.xml
jdbc/src/main/resources/TALEND-INF/local-configuration.properties

https://jira.talendforge.org/browse/TDI-45763

feat(TDI-45763):update snowflake in tck

---

jdbc/pom.xml
jdbc/src/main/java/org/talend/components/jdbc/service/I18nMessage.java
jdbc/src/main/java/org/talend/components/jdbc/service/UIActionService.java
jdbc/src/main/resources/org/talend/components/jdbc/service/Messages.properties
jdbc/src/test/java/org/talend/components/jdbc/suite/JDBCBaseContainerTest.java

https://jira.talendforge.org/browse/TDI-45543
Use new DiscoverDataset action for crawling.

feat(TDI-45543) : new DiscoverDataset action for crawling

---

pom.xml

bump component-runtime to 1.31.2

chore : bump component-runtime to 1.31.2

---

pom.xml

chore: bump locales to 1.20.2

---

azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/runtime/output/BlobWriterTest.java
azure/azureblob/src/test/java/org/talend/components/azure/dataset/AzureBlobDatasetTestIT.java
pom.xml

chore : bump to tck:1.32.0

---

common-stream-io/stream-json/pom.xml
connectors-test-bom/pom.xml
migration-tester/pom.xml
pom.xml
rest/pom.xml

Reverts Talend/connectors-se#581
*Related PR*
- https://github.com/Talend/connectors-se/pull/600
- https://github.com/Talend/cloud-components/pull/617
- https://github.com/Talend/connectors-ee/pull/266

Revert "feat(TCOMP-1892): bump spark to 3.0.1"

---

.jenkins/generate-doc.sh
.jenkins/release.sh
.jenkins/xtm-deploy.sh
Jenkinsfile

https://jira.talendforge.org/browse/TDI-45691

feat(TDI-45691): Add mvn parameters in connectors jenkins jobs

---

Jenkinsfile
pom.xml

*Related PR*
- https://github.com/Talend/connectors-se/pull/612
- https://github.com/Talend/connectors-ee/pull/330
- https://github.com/Talend/cloud-components/pull/635

chore(master)_bump_component-runtime_to_1.33.1

---

Jenkinsfile

https://jira.talendforge.org/browse/TDI-46173
This maintenance branche will be the test one to validate the fix.

feat(TDI-46173): PUSH_TO_XTM on branch only triggered manually

---

pom.xml

https://jira.talendforge.org/browse/TDI-46261

fix(TDI-46261): add different locales for asciidoc

---

common/src/main/java/org/talend/components/common/collections/IteratorComposer.java
common/src/main/java/org/talend/components/common/collections/IteratorFilter.java
common/src/test/java/org/talend/components/common/collections/IteratorComposerTest.java
common/src/test/java/org/talend/components/common/collections/IteratorFilterTest.java

https://jira.talendforge.org/browse/TDI-46281
Add simple common facilities to filter values on iterator.

TDI-46281 : add iterator filter

---

azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/common/format/avro/AvroConverterTest.java
azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/output/OuputTestIT.java
azure/azureblob/src/test/java/org/talend/components/azure/output/AvroOutputIT.java
azure/azureblob/src/test/java/org/talend/components/azure/output/ParquetOutputIT.java
azure/azureblob/src/test/java/org/talend/components/azure/runtime/converters/AvroConverterTest.java
couchbase/src/test/java/org/talend/components/couchbase/TestData.java

https://jira.talendforge.org/browse/TDI-46313
=> code must not reference SchemaImpl nor EntryImpl nor RecordImpl in unit test

TDI-46313 : remove schema impl ref in unit test

---

jdbc/src/main/java/org/talend/components/jdbc/service/JdbcService.java

https://jira.talendforge.org/browse/TDI-46344

feat(TDI-46344): change visibility to getDriver

---

Jenkinsfile
ci/Jenkinsfile-scan

https://jira.talendforge.org/browse/TDI-46325
*Related PR*
- https://github.com/Talend/connectors-se/pull/633
- https://github.com/Talend/connectors-ee/pull/381
- https://github.com/Talend/cloud-components/pull/674

feat(TDI-46325): add efs m2

---

dynamics-crm/pom.xml

https://jira.talendforge.org/browse/TDI-46262

feat(TDI-46262): bump talend-mscrm

---

dynamics-crm/pom.xml

Revert "feat(TDI-46262): bump talend-mscrm"

---

dynamics-crm/pom.xml

https://jira.talendforge.org/browse/TDI-46262

feat(TDI-46262): bump dynamics-crm to talend-mscrm:3.8-20210629

---

dynamics-crm/pom.xml

https://jira.talendforge.org/browse/TDI-46262

feat(TDI-46262): tck/dynamics bump to talend-mscrm:3.8-20210707

---

jdbc/pom.xml
jdbc/src/main/java/org/talend/components/jdbc/input/AbstractInputEmitter.java
jdbc/src/main/java/org/talend/components/jdbc/service/JdbcService.java
jdbc/src/test/java/org/talend/components/jdbc/suite/JDBCBaseContainerTest.java
jdbc/src/test/java/org/talend/components/jdbc/suite/containers/MSSQLContainerTest.java

Added Apache Calcite dependency and added nodes count validation

fix(TDI-46715): JDBC connector non readonly queries error

---

azure/azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/runtime/output/JsonBlobWriterTest.java
azure/azurecommon/pom.xml

* apache.poi-ooxml 4.0.1->4.1.2
* com.monitorjbl:xlsx-streamer 2.1.0->2.2.0
* 
Link: https://jira.talendforge.org/browse/TDI-47689

chore(TDI-47689): bump poi-ooxml

---

pom.xml

* align netty v4
Related:
tcompv0
https://github.com/Talend/components/pull/2043
tck
https://github.com/Talend/connectors-se/pull/811
https://github.com/Talend/connectors-ee/pull/594
https://github.com/Talend/cloud-components/pull/959

chore(TDI-47690): bump netty v4

---

common-stream-io/stream-json/src/test/java/org/talend/components/common/stream/input/json/JsonToSchemaTest.java
pom.xml

https://jira.talendforge.org/browse/TDI-47912
**Related PR**
- https://github.com/Talend/connectors-ee/pull/625
- https://github.com/Talend/connectors-se/pull/838
- https://github.com/Talend/cloud-components/pull/991

feat(TDI-47912): bump component-runtime to 1.44.3

---

pom.xml

https://jira.talendforge.org/browse/TDI-48761
**Related PR**
- https://github.com/Talend/connectors-se/pull/946
- https://github.com/Talend/connectors-ee/pull/785
- https://github.com/Talend/cloud-components/pull/1118

feat(TDI-48761): bump component-runtime to 1.50.0

---

couchbase/pom.xml

https://jira.talendforge.org/browse/TDI-49484

fix(TDI-49484): fix cve for couchbase core-io.
