Talend/connectors-se

jdbc/pom.xml, jdbc/src/test/resources/testcontainers.properties, pom.xml
Merge integration branch for bumping tacokit version.
See https://github.com/Talend/connectors-se/pull/92
=> chore: Bump component runtime to 1.1.6. (#92)

jdbc/src/main/resources/org/talend/components/jdbc/output/Messages.properties
Related to TFD-7031 -- our vocabulary prefers "destination" to "sink".   I used "Output" to be consistent with every other component.
=> fix(TFD-7340): Rename sinks to Output for consistency.

jdbc/src/main/resources/TALEND-INF/local-configuration.properties
I proposed a fix for TDI-42102 on master -- I'm not entirely sure it's the right thing to do, but we are certain that we don't want Derby database types on remote engines for Pipeline Designer (or Cloud Engine).  We can deactivate it in the 1.0.2 release and the change will be picked up before GA.
*_This is maintenance/1.0 only._*
For future releases, the component-server flag should be used.
=> fix(TDI-42102): Disable Derby for all 1.0.2 remote engines.

jdbc/src/main/resources/TALEND-INF/local-configuration.properties
See https://jira.talendforge.org/browse/TDI-42102
The EmbeddedDriver class is in the derby artifact (present in config).
The ClientDriver class (present in config)  is in the derbyclient artifact.
=> fix(TDI-42102): Use the derbyclient artifact.

azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/datastore/SharedKeyCredentialsUtilsTest.java
SharedKey generation returns different values on distinct JRE.
=> fix failing SharedKey tests on CI

couchbase/src/main/java/org/talend/components/couchbase/output/CouchbaseOutput.java, couchbase/src/test/java/org/talend/components/couchbase/output/CouchbaseOutputTest.java
https://jira.talendforge.org/browse/TDI-43114 - handle null values in CouchbaseOutput
We add the same issue in azure-dls-gen2 with the JsonConverter and Record processing.
=> fix(TDI-43114): handle incoming null values in CouchbaseOuput

couchbase/src/main/java/org/talend/components/couchbase/output/CouchbaseOutput.java, couchbase/src/test/java/org/talend/components/couchbase/output/CouchbaseOutputTest.java
https://jira.talendforge.org/browse/TDI-43115 - handle BYTES type in CouchbaseOuput
BYTES type is not handed and throws an IllegalArgumentException. Add a default implementation that works in studio.
=> fix(TDI-43115): handle BYTES type in CouchbaseOuput

azure-dls-gen2/pom.xml, azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/common/format/csv/CsvConfiguration.java, azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/common/format/csv/CsvConverter.java, azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/formatter/CsvContentFormatter.java, azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/AdlsGen2Service.java
https://jira.talendforge.org/browse/TDI-43392
Upgrade hadoop-commons library version to the latest version. 3.2.1 (https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-common/3.2.1)
Fix compile errors.
=> fix(TDI-43392): upgrade hadoop-commons version to 3.2.1

netsuite/src/test/java/org/talend/components/netsuite/source/NetSuiteSourceTest.java
The goal is to disable long running 'Partition input' test
https://jira.talendforge.org/browse/TDI-40709
=> feat(TDI-40709): Netsuite. disable long partition test

netsuite/src/test/java/org/talend/components/netsuite/processor/NetSuiteOutputProcessorTest.java, netsuite/src/test/java/org/talend/components/netsuite/service/NetSuiteClientConnectionServiceTest.java, netsuite/src/test/java/org/talend/components/netsuite/service/UIActionServiceTest.java, netsuite/src/test/java/org/talend/components/netsuite/source/NetSuiteSourceTest.java
It enables tests after 'invalid login attempt' was fixed
=> feat(TDI-40709): Netsuite. enable tests

jdbc/src/main/java/org/talend/components/jdbc/output/statement/operations/snowflake/SnowflakeDelete.java
https://jira.talendforge.org/browse/TDI-44020
Delete statement is generated without spaces between operation keys.
Fix joining of several operation keys
=> fix(TDI-44020): add spaces before and after

pom.xml
Bump spotbugs to 4.0.0 RC1 no more available.
=> bump spotbugs version to 4.0.0 RC1 not available at all

cosmosDB/src/main/java/org/talend/components/cosmosDB/input/CosmosDBInput.java, cosmosDB/src/main/java/org/talend/components/cosmosDB/input/CosmosDBInputConfiguration.java, cosmosDB/src/main/resources/org/talend/components/cosmosDB/input/Messages.properties
**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-44119
CosmosDB cannot transfer array with Integer and Double values.
**What is the new behavior?**
JsonToRecord now support an option to infer number type of force them to double, it has to be used by connectors. Need to be supported by CosmosDB
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:
=> feat(TDI-44119): CosmosDB support of jsonToRecord number type option

pom.xml
We can't remove I18n method since it make the build fail because locales _EN is use for validation.
=> Use root locales validation

pubsub/pom.xml
A wrong version of this epoll dependency was used in grpc-netty, and it led to class cast exception. See the JIRA comment for more details.
=> fix(TFD-11651): add the epoll native 4.1.48-Final to pubsub component

couchbase/src/main/java/org/talend/components/couchbase/output/CouchbaseOutput.java, couchbase/src/main/java/org/talend/components/couchbase/source/CouchbaseInput.java
Fix to avoid Jackson serialization error for unknown type (Couchbase JsonValue.NULL), that prevents Couchbase partial update function to complete.
https://jira.talendforge.org/browse/TDI-44747
=> fix(TDI-44747): fix serialization error, unused import removed.

extensions/polling/src/main/java/org/talend/components/extension/polling/internal/PollingComponentExtension.java
There were a NPE when using REST in streaming mode.
https://jira.talendforge.org/browse/TDI-44955
=> fix(TDI-44955) : retrieve polling parameters in instanciator.

couchbase/src/main/java/org/talend/components/couchbase/source/CouchbaseInput.java
https://jira.talendforge.org/browse/TDI-45211
Fix to Couchbase component: avoid null values being retrieved when extracting binary documents with query type "DocumentID"
=> fix(TDI-45211):  Null values returned while getting the binary document if query type is DocumentID

pom.xml
https://jira.talendforge.org/browse/TDI-45519
Jacoco plugin update on pom.xml to work near as on connectors-ee
[Jenkins log](https://jenkins-connectors.datapwn.com/job/connectors%20ee/job/build/job/master/314/consoleFull) don't contains warning anymore.
=> TDI-45519 : jacoco

common-stream-io/stream-line/src/test/java/org/talend/components/common/stream/output/line/LineValueBuilder.java, common-stream-io/stream-line/src/test/java/org/talend/components/common/stream/output/line/RecordSerializerLineHelperTest.java, marketo/src/test/java/org/talend/components/marketo/MarketoBaseTestIT.java, marketo/src/test/java/org/talend/components/marketo/dataset/MarketoInputConfigurationTest.java, marketo/src/test/java/org/talend/components/marketo/datastore/MarketoDataStoreTest.java, marketo/src/test/java/org/talend/components/marketo/input/LeadSourceTest.java, marketo/src/test/java/org/talend/components/marketo/service/UIActionServiceTestIT.java, pom.xml
https://jira.talendforge.org/browse/TDI-45574
Also, fixed some code formatting and missing licenses.
*Related PR*
- https://github.com/Talend/connectors-se/pull/547
- https://github.com/Talend/connectors-ee/pull/115
- https://github.com/Talend/cloud-components/pull/541
=> feat(TDI-45574): bump component-runtime to 1.29.1

azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/output/BlobWriter.java, azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/runtime/output/BlobWriterTest.java
https://jira.talendforge.org/browse/TDI-45712
In the complete method, there was a call performed on the null batch list.
Add an additional check for a non-null object.
=> fix(TDI-45712): fix NPE, add test

google-storage/src/main/java/org/talend/components/google/storage/service/BlobNameBuilder.java, google-storage/src/main/java/org/talend/components/google/storage/service/StorageImpl.java, google-storage/src/test/java/org/talend/components/google/storage/service/BlobNameBuilderTest.java, google-storage/src/test/java/org/talend/components/google/storage/service/StorageImplTest.java
https://jira.talendforge.org/browse/TDI-46001
generated google storage file name should keep extension.
(dummy.txt => dummy_<uuid>.txt; instead of dummy.txt_<uuid>)
=> TDI-46001 : generated filename keep extension

pom.xml
* updated commons-lang3 version to 3.10
=> fix(TDI-45981): NetSuite2019Input requires commons-lang3

pom.xml
https://jira.talendforge.org/browse/TDI-46098
* the same version as httpclient 4.5.13 use
https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.13
Related
https://github.com/Talend/connectors-ee/pull/310
https://github.com/Talend/cloud-components/pull/629
=> chore(TDI-46098): bump httpcore to 4.4.13

common-stream-io/stream-avro/src/main/java/org/talend/components/common/stream/AvroHelper.java, common-stream-io/stream-avro/src/main/java/org/talend/components/common/stream/Constants.java, common-stream-io/stream-avro/src/main/java/org/talend/components/common/stream/input/avro/AvroToRecord.java, common-stream-io/stream-avro/src/main/java/org/talend/components/common/stream/input/avro/AvroToSchema.java, common-stream-io/stream-avro/src/main/java/org/talend/components/common/stream/output/avro/RecordToAvro.java, common-stream-io/stream-avro/src/main/java/org/talend/components/common/stream/output/avro/SchemaToAvro.java, common-stream-io/stream-avro/src/test/java/org/talend/components/common/stream/input/avro/AvroToRecordTest.java, common-stream-io/stream-avro/src/test/java/org/talend/components/common/stream/output/avro/RecordToAvroTest.java
for: https://jira.talendforge.org/browse/TDI-47538
tAzureAdlsGen2Output write and read bigdecimal type in parquet type
=> fix(TDI-47538): tAzureAdlsGen2Output component converts BigDecimal to String

pom.xml
https://jira.talendforge.org/browse/TDI-50450
=> fix(TDI-50450): CVE upgrade snappy-java to 1.1.10.5
